name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: "trust"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # get the current siuba release
      - id: crnt_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: machow/siuba
          excludes: prerelease, draft
      # check it out
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.crnt_release.release }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install psycopg2~=2.8.4
          python -m pip install -r requirements-test.txt
          python -m pip install .
        env:
          REQUIREMENTS: ${{ matrix.requirements }}
      - name: Test with pytest
        run: |
          make test-travis
        env:
          SB_TEST_PGPORT: 5432

